# Generated by Django 5.2.7 on 2025-10-24 10:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_calls_initiated', models.IntegerField(default=0)),
                ('total_calls_picked', models.IntegerField(default=0)),
                ('total_calls_disconnected', models.IntegerField(default=0)),
                ('total_calls_rnr', models.IntegerField(default=0)),
                ('total_calls_failed', models.IntegerField(default=0)),
                ('total_retries', models.IntegerField(default=0)),
                ('peak_concurrent_calls', models.IntegerField(default=0)),
                ('total_call_duration_seconds', models.BigIntegerField(default=0)),
                ('dlq_entries_created', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConcurrencyControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(db_index=True, max_length=15)),
                ('campaign_id', models.IntegerField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['phone_number'], name='calls_concu_phone_n_47b137_idx'), models.Index(fields=['started_at'], name='calls_concu_started_b33146_idx')],
            },
        ),
        migrations.CreateModel(
            name='DLQEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(db_index=True, max_length=100)),
                ('payload', models.JSONField()),
                ('error', models.TextField()),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_retry_at', models.DateTimeField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='calls_dlqen_created_2df058_idx'), models.Index(fields=['processed', 'retry_count'], name='calls_dlqen_process_17007b_idx')],
            },
        ),
        migrations.CreateModel(
            name='CallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('phone_number', models.CharField(db_index=True, max_length=15)),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PROCESSING', 'Processing'), ('PICKED', 'Picked'), ('DISCONNECTED', 'Disconnected'), ('RNR', 'Ring No Response'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying'), ('COMPLETED', 'Completed')], default='INITIATED', max_length=30)),
                ('attempt_count', models.IntegerField(default=0)),
                ('max_attempts', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('next_retry_at', models.DateTimeField(blank=True, null=True)),
                ('total_call_time', models.IntegerField(blank=True, null=True)),
                ('external_call_id', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_logs', to='calls.campaign')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'next_retry_at'], name='calls_calll_status_d4fe00_idx'), models.Index(fields=['campaign', 'phone_number'], name='calls_calll_campaig_cf1412_idx'), models.Index(fields=['created_at'], name='calls_calll_created_40343e_idx')],
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(db_index=True, max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='calls.campaign')),
            ],
            options={
                'unique_together': {('campaign', 'number')},
            },
        ),
        migrations.CreateModel(
            name='RetryRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=9)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_attempts', models.IntegerField(default=3)),
                ('retry_interval_minutes', models.IntegerField(default=60)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calls.campaign')),
            ],
            options={
                'unique_together': {('campaign', 'day_of_week', 'start_time', 'end_time')},
            },
        ),
    ]
