# Generated by Django 4.2.25 on 2025-10-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllog',
            name='status',
            field=models.CharField(choices=[('INITIATED', 'Initiated'), ('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('PICKED', 'Picked'), ('DISCONNECTED', 'Disconnected'), ('RNR', 'Ring No Response'), ('FAILED', 'Failed'), ('RETRYING', 'Retrying'), ('COMPLETED', 'Completed')], default='INITIATED', max_length=30),
        ),
    ]
