global_rules:
  - name: "Weekday Business Hours"
    days: ["monday", "tuesday", "wednesday", "thursday", "friday"]
    time_slots:
      - start_time: "09:00"
        end_time: "17:00"
        max_attempts: 3
        retry_interval_minutes: 60
  
  - name: "Weekend Hours"
    days: ["saturday", "sunday"]
    time_slots:
      - start_time: "10:00"
        end_time: "23:59"
        max_attempts: 2
        retry_interval_minutes: 90

defaults:
  max_attempts: 3
  retry_interval_minutes: 60
  concurrent_call_limit: 100
  duplicate_call_window_minutes: 5

status_retry_rules:
  DISCONNECTED:
    should_retry: true
    increment_attempt: true
  RNR:
    should_retry: true
    increment_attempt: true
  PICKED:
    should_retry: false
    increment_attempt: false
  FAILED:
    should_retry: true
    increment_attempt: true
    max_attempts: 1

timezone: "UTC"

scheduler:
  check_interval_minutes: 10
  batch_size: 100
  max_concurrent_retries: 50
